version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: las_tlayudas
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d las_tlayudas"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "sh", "-c", "migrate -path /migrations -database 'postgresql://root:secret@postgres12:5432/las_tlayudas?sslmode=disable' up" ]
    volumes:
      - ./db/migration:/migrations
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres12:5432/las_tlayudas?sslmode=disable

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@postgres12:5432/las_tlayudas?sslmode=disable
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
