// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Permissions struct {
	PermissionID int32          `json:"permission_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
}

type RolePermissions struct {
	RoleID       int32     `json:"role_id"`
	PermissionID int32     `json:"permission_id"`
	AssignedAt   time.Time `json:"assigned_at"`
}

type Roles struct {
	RoleID      int32          `json:"role_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type Testimonials struct {
	TestimonialID int32     `json:"testimonial_id"`
	Title         string    `json:"title"`
	Testimonial   string    `json:"testimonial"`
	UserID        int32     `json:"user_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserRoles struct {
	UserID     int32     `json:"user_id"`
	RoleID     int32     `json:"role_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type Users struct {
	UserID            int32     `json:"user_id"`
	Firstname         string    `json:"firstname"`
	Lastname          string    `json:"lastname"`
	Password          string    `json:"password"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
