// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	CategoryID  int32
	Name        string
	Description sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Order struct {
	OrderID   int32
	OrderDate sql.NullTime
	TableID   int32
	StatusID  int32
}

type OrderProduct struct {
	OrderProductID int32
	OrderID        int32
	ProductID      int32
	Quantity       int32
}

type OrderStatus struct {
	OrderStatusID int32
	Name          string
	Description   sql.NullString
	CreatedAt     sql.NullTime
}

type Permission struct {
	PermissionID int32
	Name         string
	Description  sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Product struct {
	ProductID     int32
	Name          string
	PurchasePrice string
	SalePrice     string
	Stock         int32
	CategoryID    int32
	ProviderID    int32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Provider struct {
	ProviderID int32
	Name       string
	Phone      string
	Email      string
	Address    string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type RestaurantTable struct {
	TableID   int32
	Number    int32
	StatusID  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Role struct {
	RoleID      int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type RolePermission struct {
	RolePermissionID int32
	RoleID           int32
	PermissionID     int32
	CreatedAt        sql.NullTime
}

type TableStatus struct {
	TableStatusID int32
	Name          string
	Description   sql.NullString
	CreatedAt     sql.NullTime
}

type User struct {
	UserID    int32
	RoleID    int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
