// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (role_id, first_name, last_name, email, password, is_active)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, true))
RETURNING user_id, role_id, first_name, last_name, email, password, is_active, created_at, updated_at
`

type CreateUserParams struct {
	RoleID    int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	Column6   interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.RoleID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Column6,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, role_id, first_name, last_name, email, is_active, created_at, updated_at
FROM "user"
ORDER BY last_name, first_name
`

type GetAllUsersRow struct {
	UserID    int32
	RoleID    int32
	FirstName string
	LastName  string
	Email     string
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, role_id, first_name, last_name, email, password, is_active, created_at, updated_at
FROM "user"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, role_id, first_name, last_name, email, password, is_active, created_at, updated_at
FROM "user"
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET role_id = $2,
    first_name = $3,
    last_name = $4,
    email = $5,
    password = $6,
    is_active = $7,
    updated_at = current_timestamp
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID    int32
	RoleID    int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	IsActive  sql.NullBool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UserID,
		arg.RoleID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.IsActive,
	)
	return err
}
